### ISSUE TITLE
 Stuck on performing actions 

### ISSUE THREAD

**Issue by Youriinho** [wstyres/Zebra#260]
**Describe the bug**
The install screen ➜  Stuck on “performing actions”

**To Reproduce**
 I just wanted to update a bought theme &  remove a tweak 

**Expected behavior**

**Screenshots**
![AF8484F0-1E99-4299-91BB-7B3E35224DB6](https://user-images.githubusercontent.com/48015745/61544487-e0a6bd80-aa45-11e9-8928-be31b9583ba7.png)

**Device Information (please complete the following information):**
 - iOS Version [iOS12.1]: 
 - Zebra Version [1.0\~beta18]: 
 - Device Type [iPhone X]: 

**Crash Log or System Log**
there was no actual crash log, because after waiting for 15 minutes, I finally exited the app. 

**Additional**

**Comment by PoomSmart** [comment]
How about the latest beta? @Youriinho

**Comment by snowe2010** [comment]
Seeing the same issue on every action I do.

**Comment by SgtBreadStick** [comment]
I can confirm that I have this issue as well. Finished everything but then was stuck on Performing Actions.

I am also on latest version of Zebra on the official repo.

**Comment by wstyres** [comment]
Should be fixed as of a8cde33b5217a4fa42cfb155c28c575607a27ab2 when I re-wrote the console. It will need more testing but I will leave the issue open for further discussion.

**Comment by HuChundong** [comment]
still exist this，ios 13.2.2 checkRain， when install the viola theme
