### ISSUE TITLE
Lags while scrolling in Packages Tab

### ISSUE THREAD

**Issue by Rybo713** [wstyres/Zebra#34]
**Describe the bug**
It lags so much while scrolling in Packages Tab and in repo sections.

**Screen-Recording**
https://imgur.com/gallery/sWp1wyp

**Device Information (please complete the following information):**
 iPhone 6S+, iOS 12.0.1, Zebra 1.0b6, unc0ver JB

**Comment by wstyres** [comment]
Fixed as of 31ebe5d will be in the next beta

**Comment by relisiuol** [comment]
Not fixed. I used original project, not my fork.

https://imgur.com/a/mUNY5jj

**Comment by relisiuol** [comment]
This error is due to pagination blocking function.

Also, there is another blocking function when you click on search button.
