### ISSUE TITLE
Can't use swipe to go back gesture when refreshing repos

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#575]
**Is your feature request related to a problem? Please describe.**

I can’t swipe or tap back to the package selection page while loading repos

**Describe the solution you'd like**

It’s kind if bug but I want to swipe back to package selection. If you know what I mean. I just add screenshots and video

![9CB59E09-1A53-4516-AFB4-60A5F7EF4194](https://user-images.githubusercontent.com/40632436/68909248-0d1edc00-0791-11ea-9ff2-7da068e68330.jpeg)
![B6518E54-2012-4A6A-AEBD-870CE482A5D6](https://user-images.githubusercontent.com/40632436/68909249-0d1edc00-0791-11ea-8603-0963cc7a5b6b.jpeg)
![283A2B5C-ED09-4A68-B40D-2D79A326D3CF](https://user-images.githubusercontent.com/40632436/68909250-0d1edc00-0791-11ea-91a8-dd491aa82d8c.jpeg)

**Comment by worldlydev** [comment]
Not really a enchantment is it? This is a bug. At least for me it seems that you can't swipe to exit after Zebra started loading packages. 

![428852B4-F645-416A-AE6E-49EC95FE7F95](https://user-images.githubusercontent.com/51668635/68947212-33567300-07b5-11ea-809d-b2bae7cbcfe6.jpeg)


While the cancel button is in the top left it isn't possible to swipe. And pressing cancel does nothing.

**Comment by PoomSmart** [comment]
Fixed as of 6137c9fa2199a0846850b41497258e6ed7a1b9ea

**Comment by eve0415** [comment]
This is not fixed on beta29.
![image](https://user-images.githubusercontent.com/40632436/69471535-b3975c80-0de3-11ea-8913-4d16458a8f7e.png)

**Comment by PoomSmart** [comment]
@eve0415 Could you provided detailed steps to reproduce your issue again?

**Comment by eve0415** [comment]
1. Open Zebra and start refresh sources.
2. While refreshing open any repo.
3. Press any type of tweaks
4. You cannot swipe back to the repo types. screenshot above

**Comment by eve0415** [comment]
When finish refreshing sources, I can swipe back normally.

**Comment by PoomSmart** [comment]
@eve0415 Unable to reproduce. Are you sure you are on the latest beta?

**Comment by eve0415** [comment]
Yes, I am on the latest beta29 but I don't have time today so I will try to investigate myself on the beta 29-2 and take video tomorrow.

**Comment by eve0415** [comment]
Here watch this.
beta 29-2
https://www.dropbox.com/s/5ewpq3smp0tokf4/swipe.mp4?dl=0

**Comment by eve0415** [comment]
beta32-1
![FE17BFF0-D434-47A9-9CAB-2559D06BFF13](https://user-images.githubusercontent.com/40632436/70503997-0dc84980-1b68-11ea-93d4-624d447dead9.jpeg)

**Comment by wstyres** [comment]
Fixed in 34c6d678573d4d0c32fd9d12ebd3c6390da80699. Tested myself, this also disables pull to refresh from within a repo as that was not an intended feature and actually causes the problem.
