### ISSUE TITLE
[BUG] UI Bug - Black loading icon in dark mode

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#599]
**Describe the bug**

Same bug as #571. The difference being in how it is reproduced.

**To Reproduce**

Refresh the packages from the packages tab > go to the changes tab > scroll up. Then the loading icon will be black even though dark mode is enabled.

**Expected behavior**

I expect it to be white or the color of the tint. Lol idk what the property behavior is. I just know that it shouldn't be black at least.

**Screenshots**

Screen recording:
https://imgur.com/a/G0CDXxi

Screenshot:
![94FAD541-DB2A-4937-9F02-4BC79EE290DD](https://user-images.githubusercontent.com/51668635/69274623-07832500-0bdb-11ea-9af6-2778bad90510.jpeg)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.1.1 b3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta28-1 
 - Device Type [e.g. iPhone or iPad]: iPhone Xs
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Chimera

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

N/A

**Additional context**

iOS 13 dark mode/white tint

**Comment by worldlydev** [comment]
Update: some times you have to swipe down to show the loading icon while sometimes the black loading icon will be the before swiping down.

Also this affects the sources tab as well. Not just changes. Follow the same steps but go to the sources tab instead of the changes tab.

**Comment by PoomSmart** [comment]
Apparently fixed as of 2e51f4fd132ea5ca831a37605fb34ab00ac611f0

**Comment by worldlydev** [comment]
Not fixed for me at least. Can still reproduce this is beta 29-2.
![810E9F9D-7721-4AA7-A443-80519739B855](https://user-images.githubusercontent.com/51668635/69476296-a0cb5a80-0dd8-11ea-8f0b-69d366603e3f.jpeg)
