### ISSUE TITLE
[BUG] UI Bug - Loading icon freezes when viewing package in changes tab

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#603]
**Describe the bug**

Title really says it all.

**To Reproduce**

Refresh from the changes tab > select and view any package on the changes tab > exit that package > scroll up. The loading icon will be stuck.

**Expected behavior**

I expect the loading icon to function properly.

**Screenshots**

Screenshot:
![88EB1E4A-7A8D-45CA-AD9E-BD22EB2D8BBF](https://user-images.githubusercontent.com/51668635/69276672-2c799700-0bdf-11ea-9516-f95fa11550e3.jpeg)

Screen recording:
https://imgur.com/a/smxsavs

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.1.1 b3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
Beta 28-1
 - Device Type [e.g. iPhone or iPad]: iPhone Xs
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Chimera

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

N/A

**Additional context**

N/A

**Comment by wstyres** [comment]
Is this not the same as #573 ?

**Comment by worldlydev** [comment]
> Is this not the same as #573 ?

May very well be caused by the same issue. I have no clue. Just sharing what I noticed.

The visual bug is different though. Instead of no loading icon at all the loading icon freezes.

**Comment by eve0415** [comment]
I can confirm that. The icon will freeze. When you started refreshing in the Change Tab and went to and back from Source Tab, the icon will disappear.

**Comment by PoomSmart** [comment]
Fixed as of f6e646ec4a0c0833dd80798a2fc65ea03eaf836b

**Comment by worldlydev** [comment]
Isn't fixed for me in beta 29-2.
![A81B1551-7F8F-4B54-87EA-BEAC7F395AC4](https://user-images.githubusercontent.com/51668635/69476399-af664180-0dd9-11ea-9790-27bbebe5f3c6.jpeg)
