### ISSUE TITLE
[BUG] Some depictions still unable to view

### ISSUE THREAD

**Issue by Greigh** [wstyres/Zebra#642]
**Describe the bug**
Depictions get cut off. 

**To Reproduce**

https://apt.alfhaily.me/

One repo that shows it. 

**Expected behavior**

Show whole depiction. 

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: Beta 30 
 - Device Type [e.g. iPhone or iPad]: XS Max
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver 

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

Most depictions are fine. Only a few repos and/or packages are having issues.

**Comment by wstyres** [comment]
Should be fixed as of 0a00d4de707e968a504f23cb27acb12329dd4bff.

**Comment by worldlydev** [comment]
> Should be fixed as of [0a00d4d](https://github.com/wstyres/Zebra/commit/0a00d4de707e968a504f23cb27acb12329dd4bff).

Seems to function for alfhaily's repo now but the issue still occurs for other depictions. Such as on AlbumHider from: https://ib-soft.net/cydia/

**Comment by wstyres** [comment]
Looks like that is due to some extra javascript being run to locate the page in question instead of using static files. Because of this, my code to detect the page height is run BEFORE the actual page is fetched. I will do some research into this and report back

**Comment by wstyres** [comment]
Should be fixed in 127e679c5b1cd0b914d548b13efaf2abdb5cc8b1.

**Comment by wstyres** [comment]
Check out those depictions in 30-2, they should appear properly now.

**Comment by Greigh** [comment]
It is now fixed. I am now closing this :) Thank you @wstyres!

**Comment by lucky13820** [comment]
I am still having this issue on newest beta30-4. It happens to BigBoss repo. Although not all tweaks have this problem. Right now VideoSwipes and Zoom for YouTube are having this problem for me. You can view a screen record here. https://imgur.com/a/zsAK1Li

**Comment by wstyres** [comment]
Hopefully this is fixed again as of 905ae59e2e55730334fbb0b7b742dddd7f1fb8e5.

**Comment by wstyres** [comment]
Check to see if the issues are resolved in beta 31.

**Comment by lucky13820** [comment]
Looks like it’s fixed. Zoom for YouTube and VideoSwipes are working fine. Haven’t seen any other tweak has this issue. Thanks!
