### ISSUE TITLE
Conflict tweak does not want to be removed 

### ISSUE THREAD

**Issue by xi7i6** [wstyres/Zebra#730]
**Describe the bug**
As the title said i try to install filza when i already have the other one filza as shown below in the picture but i could not install because i got conflicting error . 

**To Reproduce**
Install one of the filza for 64 devices that packaged in this repo http://tigisoftware.com/cydia/ 
then try to install the other filza 

**Expected behavior**
A normal way to remove the conflicting packages.

**Screenshots**
![12553B01-C99F-4F98-863C-57C5F3264563](https://user-images.githubusercontent.com/55637002/71314803-c17ee280-2460-11ea-83c3-255d1bc058d0.png)
.

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: latest beta
 - Device Type [e.g. iPhone or iPad]: iphone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Unc0ver

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment]
Could you post what Zebra says when tapping on the red Filza package?

**Comment by eve0415** [comment]
![51B5C373-04C0-4EDA-A07B-A1885F12AC10](https://user-images.githubusercontent.com/40632436/71315180-f52a2e80-2499-11ea-8889-d37fece83a73.png)
The remove doesn’t come out automatically. And also “conflict with” is not localized.

**Comment by xi7i6** [comment]
![FE0033B1-662C-440F-8FA4-D96BF0C6D20C](https://user-images.githubusercontent.com/55637002/71319481-054d0880-24b0-11ea-8b8b-3a456def6b89.png)


> Could you post what Zebra says when tapping on the red Filza package?

**Comment by wstyres** [comment]
Should be fixed as of 074740dffab803b17683d81fe5f741be0495d9dc.

**Comment by eve0415** [comment]
I think it’s not fixed properly.
![33DA3CB6-B011-424B-A1F9-AC6ED1977870](https://user-images.githubusercontent.com/40632436/71328252-624fc980-2557-11ea-8ee4-75eb59ee9cd7.png)
I have installed iThemer, but it won’t come up as remove.

**Comment by eve0415** [comment]
![C8CE3972-3C8C-4B83-8099-A4045ED4C23F](https://user-images.githubusercontent.com/40632436/71328290-4ac51080-2558-11ea-9e4a-372a00622424.png)

**Comment by wstyres** [comment]
That is intended, for the time being Zebra will favor the package that is installed over the package that you are trying to install.
