### ISSUE TITLE
Purchase authorization not obtained using Quick Actions / Swipe Actions and Dependencies

### ISSUE THREAD

**Issue by lucky13820** [wstyres/Zebra#739]
**Describe the bug**
When I click the update button in the package tab, it won’t update the tweak from Dynastic repo. It will shows 401 unauthorized. But I click into the tweak and install the update in the tweak description page, everything works fine. I already logged into Dynastic repo.

**To Reproduce**
When there is an update in the tweaks in Dynastic Repo, click update in the package tab, and install the update.

**Expected behavior**
It should update normally, as I already logged into Dynastic repo. I can only update in the tweak description page. Right now I only experience this from Dynastic repo.

**Screenshots**
When I update in package tab.
![AD192365-D962-46B9-8865-BCC9CEE847D1](https://user-images.githubusercontent.com/7293811/71386061-0fe6cb00-25a0-11ea-94d7-0146d65c019b.png)

When I update in tweak description page.
![848C0DE0-0918-4854-B4DB-E87088F89F99](https://user-images.githubusercontent.com/7293811/71386068-1bd28d00-25a0-11ea-9ea0-1223bbd6c64f.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0-rc3
 - Device Type [e.g. iPhone or iPad]: iPhone XS Max 
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver 3.7.0-b4

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment]
Could you send a screen recording of the problem? It would be better to reproduce if I knew the exact steps.

**Comment by lucky13820** [comment]
Ok, do you know if there is a way to downgrade a tweak from Dynastic repo? I already updated everything.

**Comment by lucky13820** [comment]
Here is a screen recording.
https://imgur.com/a/ZcBLkSS

Merry Christmas!

**Comment by wstyres** [comment]
So this only happens with tweaks from Dynastic or does it apply to other paid package updates as well?

**Comment by lucky13820** [comment]
I only notice tweaks from Dynastic repo. All my Packix  purchases updates fine.

**Comment by wstyres** [comment]
So this looks to be a problem when determining whether or not the package is paid from the Upgrade list which is why the problem only occurs when using the Swipe Actions but not when using the button from within the package depiction. This is simply a lapse in logic and I will see what I can do to fix it.

**Comment by yur1xpp** [comment]
@wstyres This still happening on latest beta, and upgrade from within the package is the only solution.

**Comment by wstyres** [comment]
Should be fixed as of 23a5fef6241940edba21e88560256a893513ff70.

**Comment by joshpeterson1** [comment]
This is still happening for me today. AFAIK I'm on the latest Zebra version (no updates available), however I'm not able to download any Dynsatic packages on my iPad, which is both signed in and has a Dynastic profile.
