### ISSUE TITLE
[Bug] Ignore Updates not available on certain packages 

### ISSUE THREAD

**Issue by yllshahini** [wstyres/Zebra#886]
**Describe the bug**
Unable to ignore updates for Ultrasound. I have the free version installed and the update is a paid version.

**To Reproduce**
Have the free version of a package installed that has a paid update.

**Expected behavior**
Being able to ignore updates same as with other packages.

**Screenshots**
![DFCF9775-7E07-44F9-8B55-047A1BE4CA25](https://user-images.githubusercontent.com/39761205/75115102-0c34fa80-565c-11ea-903e-2243ef07d4ad.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.0.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1~beta1-1
 - Device Type [e.g. iPhone or iPad]: iPhone X
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver 3.8.0~b1

**Crash Log or System Log**
No crash log available.

**Additional context**

**Comment by wstyres** [comment]
Do the free/paid versions have different package IDs per chance?

**Comment by yllshahini** [comment]
No idea. How do I check?

**Comment by wstyres** [comment]
What is the package ID for the version you have installed / what is the package ID for the one available from Dynastic. You can see the package ID on the depiction page right underneath the name.

**Comment by yllshahini** [comment]
They both have the same ID: applebetas.ios.tweak.willow, from what I can see. 😬

**Comment by wstyres** [comment]
Ok, and what version do you have installed? What version is it trying to update to?

**Comment by yllshahini** [comment]
I have 1.2.9 installed and it's trying to update to 1.2.13.

**Comment by wstyres** [comment]
Thanks! I'll look into it.

**Comment by yllshahini** [comment]
No problem. Thanks for your hard work 😊

**Comment by PoomSmart** [comment]
Fixed as of 9a1f4468a6ceceae86a7eade3a710ca8ee4e7c5a

**Comment by yllshahini** [comment]
Just wanted to let you know this bug still persists on Zebra 1.1~beta3-1. Reset all sources and settings but to no avail. I turned off notification badges for Zebra for the time being so it doesn't bother me as much.
